tasks:
  - name: terraform
    init: |
      chmod +x ./bin/install_terraform_cli
      source ./bin/install_terraform_cli
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      chmod +x ./bin/install_aws
      source ./bin/install_aws
      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform